### ISSUE TITLE
Events image is fixed size and float by stylesheet

### ISSUE THREAD

**Issue by andybroomfield** [localgovdrupal/localgov_events#59]
Localgov_events includes some default styling to fix the size of the image and float it to the left.
As its fixed to the class, it's harder to override in a generic way.
Kind of feel this needs to move the localgov_base anyway @markconroy?

(BHCC has a smaller image thumbnail and floats to the right, and the aim is to do this generically).

````css
.views-field-localgov-event-image img,
.media--view-mode-localgov-event-thumbnail img {
  float: left;
  width: 200px;
  height: auto;
  margin: 0 1.5rem 1rem 0;
}
````
